services:
  super-simple-queues:
    build: .
    image: super-simple-queues
    environment:
      - TCP_PORT=${TCP_PORT}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - "${TCP_PORT}:${TCP_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"