services:
  super-simple-queues:
    build: .
    image: super-simple-queues
    container_name: super-simple-queues
    env_file:
      - .env
    ports:
      - "${TCP_PORT}:${TCP_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"